### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by tshemsedinov** [SergeyOcheretenko/OrderFoodBot#1]
- It would be better to use branches and pull requests, don't commit to master
- Extract text resources from code to declarative format, for example json
- It looks like not working as of review date

**Comment by SergeyOcheretenko** [comment]
Started to work in a separate branch using PR. 

I'm working on learning the JSON format so I can use it on your advice. 

Now the project is in active development, so every day is developed, refined and gets new functionality.
